# Generated by Django 4.1.1 on 2022-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement_orders',
            name='tenent_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
