# Generated by Django 4.1.1 on 2022-09-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_agreement_orders_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement_orders',
            name='payment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
