# Generated by Django 4.1.1 on 2022-09-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement_orders',
            old_name='agreement_startdate',
            new_name='agreement_start_date',
        ),
        migrations.RenameField(
            model_name='agreement_orders',
            old_name='type_of_package',
            new_name='package_type',
        ),
    ]
