# Generated by Django 4.1.1 on 2022-09-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_bluit_area_unit_agreement_orders_landlord_building_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement_orders',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='agreement_orders',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agreement_orders',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
