# Generated by Django 4.1.1 on 2022-09-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_agreement_orders_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement_orders',
            name='user_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
