# Generated by Django 4.1.1 on 2022-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_agreement_orders_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
