# Generated by Django 4.1.1 on 2022-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_coupon_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement_orders',
            name='coupan',
            field=models.CharField(blank=True, default='None', max_length=1000, null=True),
        ),
    ]
