# Generated by Django 4.1.1 on 2022-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_agreement_orders_coupan'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement_orders',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
